import Pilot from "../../components/Pilot/Pilot";
import PilotList from "../../components/PilotsList/PilotsList";

export default function() {

  return (
    <PilotList 
      pilotDatas={data}
    />
  )
}

const data = [
  {
    id: 1,
    airline: "737",
    fleet: "73gG",
    seat: "CPT",
    domicile: "GEG",
    firstName: "John",
    lastName: "Smith",
    email: "superghost0621",
    areacode: "32/106",
    prefix: "Riviera",
    suffix: "State",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Frabcusco",
    state: "CA 94107",
    postalCode: "94107",
  },
  {
    id: 1,
    airline: "737",
    fleet: "73gG",
    seat: "CPT",
    domicile: "GEG",
    firstName: "John",
    lastName: "Smith",
    email: "superghost0621",
    areacode: "32/106",
    prefix: "Riviera",
    suffix: "State",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Frabcusco",
    state: "CA 94107",
    postalCode: "94107",
  },
  {
    id: 1,
    airline: "737",
    fleet: "73gG",
    seat: "CPT",
    domicile: "GEG",
    firstName: "John",
    lastName: "Smith",
    email: "superghost0621",
    areacode: "32/106",
    prefix: "Riviera",
    suffix: "State",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Frabcusco",
    state: "CA 94107",
    postalCode: "94107",
  },
  {
    id: 1,
    airline: "737",
    fleet: "73gG",
    seat: "CPT",
    domicile: "GEG",
    firstName: "John",
    lastName: "Smith",
    email: "superghost0621",
    areacode: "32/106",
    prefix: "Riviera",
    suffix: "State",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Frabcusco",
    state: "CA 94107",
    postalCode: "94107",
  },
  {
    id: 1,
    airline: "737",
    fleet: "73gG",
    seat: "CPT",
    domicile: "GEG",
    firstName: "John",
    lastName: "Smith",
    email: "superghost0621",
    areacode: "32/106",
    prefix: "Riviera",
    suffix: "State",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Frabcusco",
    state: "CA 94107",
    postalCode: "94107",
  },
  {
    id: 1,
    airline: "737",
    fleet: "73gG",
    seat: "CPT",
    domicile: "GEG",
    firstName: "John",
    lastName: "Smith",
    email: "superghost0621",
    areacode: "32/106",
    prefix: "Riviera",
    suffix: "State",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Frabcusco",
    state: "CA 94107",
    postalCode: "94107",
  },
  {
    id: 1,
    airline: "737",
    fleet: "73gG",
    seat: "CPT",
    domicile: "GEG",
    firstName: "John",
    lastName: "Smith",
    email: "superghost0621",
    areacode: "32/106",
    prefix: "Riviera",
    suffix: "State",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Frabcusco",
    state: "CA 94107",
    postalCode: "94107",
  },
  {
    id: 1,
    airline: "737",
    fleet: "73gG",
    seat: "CPT",
    domicile: "GEG",
    firstName: "John",
    lastName: "Smith",
    email: "superghost0621",
    areacode: "32/106",
    prefix: "Riviera",
    suffix: "State",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Frabcusco",
    state: "CA 94107",
    postalCode: "94107",
  },
  {
    id: 1,
    airline: "737",
    fleet: "73gG",
    seat: "CPT",
    domicile: "GEG",
    firstName: "John",
    lastName: "Smith",
    email: "superghost0621",
    areacode: "32/106",
    prefix: "Riviera",
    suffix: "State",
    address1: "795 Folsom Ave",
    address2: "Suite 600",
    city: "San Frabcusco",
    state: "CA 94107",
    postalCode: "94107",
  },
]